# Q-Table Learning

In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

[2017-04-04 21:11:17,798] Making new env: FrozenLake-v0


In [9]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        print("s1rd", s1, r, d)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

s1rd 4 0.0 False
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 8 0.0 False
s1rd 12 0.0 True
s1rd 4 0.0 False
s1rd 5 0.0 True
s1rd 1 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 1 0.0 False
s1rd 5 0.0 True
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 4 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 4 0.0 False
s1rd 5 0.0 True
s1rd 1 0.0 False
s1rd 2 0.0 False
s1rd 3 0.0 False
s1rd 3 0.0 False
s1rd 7 0.0 True
s1rd 0 0.0 False
s1rd 4 0.0 False
s1rd 8 0.0 False
s1rd 9 0.0 False
s1rd 5 0.0 True
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 1 0.0 False
s1rd 1 0.0 False
s1rd 2 0.0 False
s1rd 3 0.0 False
s1rd 3 0.0 False
s1rd 3 0.0 False
s1rd 2 0.0 False
s1rd 6 0.0 False
s1rd 7 0.0 True
s1rd 0 0.0 False
s1rd 0 0.0 False
s1rd 1 0.0 False
s1rd 2 0.0 False
s1rd 2 0.0 False
s1rd 1 0.0 False
s1rd 1 0.0 False
s1rd 1 0.0 False
s1r

In [4]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.468


In [5]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  6.15113878e-01   1.97254009e-03   1.44931567e-03   2.53741927e-03]
 [  2.42287972e-04   1.01108773e-03   1.59648320e-05   5.21805374e-01]
 [  1.44026601e-04   4.79356910e-01   4.79689710e-04   0.00000000e+00]
 [  1.39004162e-03   3.65177310e-04   2.15076781e-04   3.06517267e-01]
 [  6.52354739e-01   1.42619279e-03   1.35506514e-04   4.58118102e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.38463615e-05   1.00910029e-05   4.14925786e-02   4.80085642e-11]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.95915979e-04   1.30441361e-04   1.52984268e-03   5.36921558e-01]
 [  3.93488006e-04   2.16156411e-01   6.68814621e-05   1.08954239e-04]
 [  2.66647330e-01   5.07975760e-04   3.40395328e-04   4.04332713e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.24175258e-01   0